### ISSUE TITLE
IPv6 as Server does not work: dnsping -c 42  -fixed-id 42 -json sampleResult.json -c 8 www.google.com 2001:4860:4860::8888

### ISSUE THREAD

**Issue by grzchr15** [fortio/dnsping#6]
Ipv4 is working but Ipv6 dns server not

dnsping -c 42  -fixed-id 42 -json sampleResult.json -c 8 www.google.com 2001:4860:4860::8888
19:11:06 I dnsping dev: will query 8 times, sleeping 1s in between, the server 2001:4860:4860::8888:53 for A (1) record for www.google.com.
19:11:06 E   0.0 ms   1: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:07 E   0.0 ms   2: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:08 E   0.0 ms   3: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:09 E   0.0 ms   4: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:10 E   0.0 ms   5: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:11 E   0.0 ms   6: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:12 E   0.0 ms   7: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
19:11:13 E   0.0 ms   8: failed call: dial udp: address 2001:4860:4860::8888:53: too many colons in address
8 errors (100.00%), 0 success.
response time (in ms) : count 8 avg 0 +/- 0 min 0 max 0 sum 0
# range, mid point, percentile, count
>= 0 <= 0 , 0 , 100.00, 8
# target 50% 0
# target 90% 0
# target 99% 0
Successfully wrote 724 bytes of Json data to sampleResult.json

dnsping -c 42  -fixed-id 42 -json sampleResult.json -c 8 www.google.com 8.8.8.8
19:12:14 I dnsping dev: will query 8 times, sleeping 1s in between, the server 8.8.8.8:53 for A (1) record for www.google.com.
19:12:14 I  15.6 ms   1: [www.google.com.       184     IN      A       172.217.19.100]
19:12:15 I  15.9 ms   2: [www.google.com.       184     IN      A       172.217.16.100]
19:12:16 I  15.7 ms   3: [www.google.com.       249     IN      A       216.58.214.196]
19:12:17 I  16.8 ms   4: [www.google.com.       182     IN      A       172.217.20.4]
19:12:18 I  15.8 ms   5: [www.google.com.       180     IN      A       172.217.19.100]
19:12:19 I  16.5 ms   6: [www.google.com.       182     IN      A       172.217.19.100]
19:12:20 I  15.8 ms   7: [www.google.com.       261     IN      A       172.217.20.4]
19:12:21 I  15.7 ms   8: [www.google.com.       177     IN      A       172.217.16.100]
0 errors (0.00%), 8 success.
response time (in ms) : count 8 avg 16.006315 +/- 0.4021 min 15.639415999999999 max 16.832446 sum 128.050519
# range, mid point, percentile, count
>= 15.6394 <= 16 , 15.8197 , 75.00, 6
> 16 <= 16.8324 , 16.4162 , 100.00, 2
# target 50% 15.8558
# target 90% 16.4995
# target 99% 16.7991
Successfully wrote 939 bytes of Json data to sampleResult.json

**Comment by ldemailly** [comment]
thanks for the report, will fix it's easy/my bad concatenating without check ipv6

**Comment by ldemailly** [comment]
workaround is easy in meantime: use "[2001:4860:4860::8888]" for server

but then I get:
14:31:40 E   0.0 ms   1: failed call: write udp [fe80::aede:48ff:fe00:1122%utun7]:63129->[2001:4860:4860::8888]:53: write: no buffer space available

**Comment by ldemailly** [comment]
the error was because of my vpn, fix incoming

**Comment by ldemailly** [comment]
fixed in https://github.com/fortio/dnsping/releases/tag/v1.1.4
```
dnsping -c 3  -q aaaa www.google.com "2001:4860:4860::8888"
15:58:05 I Adding [] around detected input IPv6 server ip info: [2001:4860:4860::8888]
15:58:05 I dnsping dev: will query 3 times, sleeping 1s in between, the server [2001:4860:4860::8888]:53 for AAAA (28) record for www.google.com.
15:58:05 I  21.5 ms   1: [www.google.com.	199	IN	AAAA	2607:f8b0:4005:809::2004]
15:58:06 I  18.9 ms   2: [www.google.com.	159	IN	AAAA	2607:f8b0:4005:807::2004]
15:58:07 I  25.7 ms   3: [www.google.com.	197	IN	AAAA	2607:f8b0:4005:809::2004]
```
